### ISSUE TITLE
With Version23: behind a reverse proxy and the overwrite config variables are not set correctly

### ISSUE THREAD

**Issue by JoergHein** [nextcloud/docker#1672]
Hello, 

I installed my Nextcloud via Docker Image.
With the new version 23, I have the following problem.

"You are accessing your instance over a secure connection, however your instance is generating insecure URLs. This most likely means that you are behind a reverse proxy and the overwrite config variables are not set correctly"

I have the last changes in the Dockerfile and in the docker-compose.yml according to example:

https://github.com/nextcloud/docker/tree/master/.examples/docker-compose/with-nginx-proxy/mariadb/apache

updated on my server.
Nevertheless, the message mentioned above still occurs.

Does anyone have a solution for me?
Thanks and Regards

**Comment by anshibanov** [comment]
+1 same issue

**Comment by BryanEmmerson** [comment]
Set the `OVERWRITEPROTOCOL` environment variable for you Nextcloud service to `https` (see section *Using the apache image behind a reverse proxy and auto configure server host and protocol* on the [official Nextcloud docker page](https://hub.docker.com/_/nextcloud/).

I also set the `TRUSTED_PROXIES` variable, but I don't think this is strictly necessary for the above issue.

**Comment by JoergHein** [comment]
Shouldn't the error be better fixed in the Docker configuration?
The error did not occur before version 23.0 and I use the default configuration.

**Comment by Xanarkan** [comment]
Yup, same error since 23.0 and I didn't have it before.
That kind of thing occurring when you use the official Docker image with the official docker-compose file is a bit disturbing.
Isn't possible to fix this directly in the image so we don't have to weak it after install and risk having to do it again when we update the container or when we recreate it ?

**Comment by ouankou** [comment]
Recently I just deployed NextCloud 23 and MariaDB 10.6 using docker-compose. A similar issue was encountered. My solution is something as follows.

Assume you've set Apache domain proxy on the host properly, requests to `yourdomain.com` will be forwarded to the actual NextCloud host on 127.0.0.1:8080. 

1. Add the following attributes to `config.php`: 
```php
  'trusted_domains' => 
  array (
    0 => 'yourdomain.com',
  ),
  'trusted_proxies' => 
  array (
    0 => 'yourdomain.com',
  ),
  'overwrite.cli.url' => 'https://yourdomain.com',
  'overwriteprotocol' => 'https',
```

2. Restart docker-compose. The warning should be gone.

**Comment by thomasmerz** [comment]
I had to fix both "overwrite…" lines (add line overwriteprotocol and fix http to https in line overwrite.cli.url). Both "trusted…" lines were already correct. Now this is also fixed for me. Thank you very much @ouankou 🤗

**Comment by donhauser** [comment]
I think `overwrite.cli.url` can be set by the `OVERWRITECLIURL` environment variable (did not test it though).

The file `config/reverse-proxy.config.php` contains the following php code, which is also used for other env-variables like `OVERWRITEHOST` and `OVERWRITEPROTOCOL`:

```php
$overwriteCliUrl = getenv('OVERWRITECLIURL');
if ($overwriteCliUrl) {
  $CONFIG['overwrite.cli.url'] = $overwriteCliUrl;
}
```

Setting variables in `docker-compose.yml`:
```
nextcloud:
  image: nextcloud:23
  [...]
  environment:
    - TRUSTED_PROXIES=yourdomain.com
    - OVERWRITECLIURL=https://yourdomain.com
    - OVERWRITEPROTOCOL=https
    # I think this hooks in at a slightly different place
    - NEXTCLOUD_TRUSTED_DOMAINS=yourdomain.com
    # maybe you also want this
    - OVERWRITEHOST=yourdomain.com
```

*PS: If you are annoyed by repeatedly entering your domain, you can use an `.env` file and the [`VAR=${VAR}`- syntax](https://docs.docker.com/compose/environment-variables/)*

**Comment by heinrichmartin** [comment]
This issue is closed, and I am on branch `master`, but I am still seeing this issue in `postgres/fpm`. With the technical details by @ouankou and the solution by @donhauser, I was able to fix it _cleanly_.

Has anyone considered a PR? Should this issue be re-opened? Or create another one?

(I am not on a fork, and I came to this setup only today; so I have no clue about other files to be fixed, sorry. Btw, a big thank you for the great work - this is a solid config that is fun to apply! :partying_face:)

```
diff --git a/.examples/docker-compose/with-nginx-proxy/postgres/fpm/docker-compose.yml b/.examples/docker-compose/with-nginx-proxy/postgres/fpm/docker-compose.yml
index 6e41174..6713b2a 100644
--- a/.examples/docker-compose/with-nginx-proxy/postgres/fpm/docker-compose.yml
+++ b/.examples/docker-compose/with-nginx-proxy/postgres/fpm/docker-compose.yml
@@ -21,6 +21,7 @@ services:
     environment:
       - POSTGRES_HOST=db
       - REDIS_HOST=redis
+      - OVERWRITEPROTOCOL=https
     env_file:
       - db.env
     depends_on:
```

**Comment by HHUBSS** [comment]
> Recently I just deployed NextCloud 23 and MariaDB 10.6 using docker-compose. A similar issue was encountered. My solution is something as follows.
> 
> Assume you've set Apache domain proxy on the host properly, requests to `yourdomain.com` will be forwarded to the actual NextCloud host on 127.0.0.1:8080.
> 
> 1. Add the following attributes to `config.php`:
> 
> ```
>   'trusted_domains' => 
>   array (
>     0 => 'yourdomain.com',
>   ),
>   'trusted_proxies' => 
>   array (
>     0 => 'yourdomain.com',
>   ),
>   'overwrite.cli.url' => 'https://yourdomain.com',
>   'overwriteprotocol' => 'https',
> ```
> 
> 2. Restart docker-compose. The warning should be gone.

I followed this. I can access nextcloud thru public domain but I can't access it locally using http or https

**Comment by sohaib1khan** [comment]
> 

Thank you soooo much!! worked for me

**Comment by sanctimon** [comment]
I used to have Nextcloud installed on TOS (TerraMaster).

This was my config file:

```
<?php
$CONFIG = array (
  'instanceid' => '***',
  'passwordsalt' => '***',
  'datadirectory' => '/***/nextcloud/data',
  'version' => '25.0.3.2',
  'dbtype' => 'mysql',
  'dbhost' => 'localhost:/tmp/mysql.sock',
  'dbport' => '',
  'dbname' => '***',
  'dbuser' => '***',
  'dbpassword' => '***',
  'dbtableprefix' => 'oc_',
  'mysql.utf8mb4' => true,
  'filelocking.enabled' => true,
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'memcache.locking' => '\\OC\\Memcache\\Redis',
  'redis' =>
  array (
    'host' => '127.0.0.1',
    'port' => 6379,
  ),
  'installed' => true,
  'default_language' => 'en',
  'default_locale' => 'en_GB',
  'defaultapp' => 'dashboard,files',
  'knowledgebaseenabled' => true,
  'allow_user_to_change_display_name' => true,
  'remember_login_cookie_lifetime' => 1296000,
  'auth.bruteforce.protection.enabled' => true,
  'mail_domain' => '***',
  'mail_smtpmode' => 'smtp',
  'mail_smtphost' => '***',
  'mail_smtpport' => '465',
  'mail_smtpauth' => 1,
  'mail_smtpauthtype' => 'PLAIN',
  'mail_smtpname' => '***',
  'mail_smtppassword' => '***',
  'theme' => '',
  'default_phone_region' => 'GB',
  'loglevel' => 2,
  'maintenance' => false,
  'trusted_domains' =>
  array (
    0 => 'local.network.url:httpsport',
    1 => 'local.network.url:httpport',
    2 => 'public.url',
  ),
  0 =>
  array (
    'trusted_proxies' => 'reverse.proxy.local.ip',
    'overwritehost' => 'public.url.net:443',
    'overwriteprotocol' => 'https',
    'overwritewebroot' => '/',
    'overwrite.cli.url' => 'https://public.url.net/',
   #'overwrite.cli.url' => 'https://localhost:31443',
    'htaccess.RewriteBase' => '/',
    'ProxyPreserveHost' => 'On',
  ),
  'forwarded_for_headers' =>
  array (
    0 => 'HTTP_X_FORWARDED_FOR',
    1 => 'HTTP_X_FORWARDED',
  ),
  'secret' => '***',
  'mail_from_address' => 'admin',
  'mail_sendmailmode' => 'smtp',
  'mail_smtpsecure' => 'ssl',
);
```
This worked well, **BUT**: Nextcloud was actually listening on https (port 31443) on its host, not the reverse proxy. This meant that the reverse proxy reached out to the nextcloud instance on https, not http. This did away with the message: _

> You are accessing your instance over a secure connection, however your instance is generating insecure URLs.

_

Now with Nextcloud on docker, it is impossible to make Nextcloud to also listen on https. Most posts I have seen are extremely confusing and start talking about installing certificates. However, in the case of reverse proxy, the certificates are alive and well and fully functional on the reverse proxy server. I still have not figured out how to get nextcloud on docker to listen on https.
