### ISSUE TITLE
[Bug]: DNS `/etc/resolv.conf`'s `options: ndots:X` is not respected

### ISSUE THREAD

**Issue by georglauterbach** [nextcloud/docker#2293]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

I run NC `docker.io/nextcloud:29.0.6-apache` in Kubernetes. With `dnsOptions` I set `ndots:1`, which shows up in `/etc/resolv.conf` inside the NC pod. When looking at the DNS server logs, though, I can clearly see that the search domains `search <NAMESPACE>.svc.cluster svc.cluster cluster` are appended to _all_ DNS queries (even those where the number of dots is > 1`:

```txt
CNAME IN pushfeed.nextcloud.com.cloud.svc.cluster udp
CNAME IN pushfeed.nextcloud.com.svc.cluster udp
CNAME IN pushfeed.nextcloud.com.cluster udp
```

This is clearly a violation of the DNS options for this pod. I was unable to find documentation about such a setting in the NC configuration.

### Steps to reproduce

1. Set `ndots:1` in `/etc/resolv.conf`
2. Set `search XX.YY.ZZ YY.ZZ ZZ` in `/etc/resolv.conf`
3. Observe that queries, like `pushfeed.nextcloud.com` (number of dots = 2), are treated as having no dots, hence appending the search domains XX.YY.ZZ, YY.ZZ, ZZ

### Expected behavior

Queries with the number of dots >= value of `ndots:` in `/etc/resolv.conf` should be treated with the correct number of dots, hence not appending search domains.

### Nextcloud Server version

29

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.3

### Web server

Apache (supported)

### Database engine version

PostgreSQL

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
If required, I can deliver this later (cannot copy from my current machine due to only having a VNC console...)
```

### List of activated Apps

```shell
If required, I can deliver this later (cannot copy from my current machine due to only having a VNC console...)
```

### Nextcloud Signing status

```shell
If required, I can deliver this later (cannot copy from my current machine due to only having a VNC console...)
```

### Nextcloud Logs

```shell
If required, I can deliver this later (cannot copy from my current machine due to only having a VNC console...)
```

**Comment by georglauterbach** [comment]
I have parsed the log of my DNS server, CoreDNS, which logs a line when it was unable to complete a request (mostly logging `NXDOMAIN` or `NOERROR`):

```console
$ { while read -r d _ _ _ RECORD _ HOST _ _ _ _ RESULT _; do printf "%5s -> %s\n" "${RECORD#\"}" "${HOST} ${RESULT}"; done < <(k logs -n dns coredns-5679c4f864-rc44p --container coredns | grep cloud) ; } |& sort | uniq
    A -> apps.nextcloud.com.cloud.svc.cluster. NXDOMAIN
    A -> apps.nextcloud.com.cluster. NXDOMAIN
    A -> apps.nextcloud.com.svc.cluster. NXDOMAIN
    A -> nextcloud.com.cloud.svc.cluster. NXDOMAIN
    A -> nextcloud.com.cluster. NXDOMAIN
    A -> nextcloud.com.svc.cluster. NXDOMAIN
    A -> push-notifications.nextcloud.com.cloud.svc.cluster. NXDOMAIN
    A -> push-notifications.nextcloud.com.cluster. NXDOMAIN
    A -> push-notifications.nextcloud.com.svc.cluster. NXDOMAIN
    A -> pushfeed.nextcloud.com.cloud.svc.cluster. NXDOMAIN
    A -> pushfeed.nextcloud.com.cluster. NXDOMAIN
    A -> pushfeed.nextcloud.com.svc.cluster. NXDOMAIN
    A -> updates.nextcloud.com.cloud.svc.cluster. NXDOMAIN
    A -> updates.nextcloud.com.cluster. NXDOMAIN
    A -> updates.nextcloud.com.svc.cluster. NXDOMAIN
    A -> www.nextcloud.com.cloud.svc.cluster. NXDOMAIN
    A -> www.nextcloud.com.cluster. NXDOMAIN
    A -> www.nextcloud.com.svc.cluster. NXDOMAIN
CNAME -> apps.nextcloud.com. NOERROR
CNAME -> apps.nextcloud.com.cloud.svc.cluster. NXDOMAIN
CNAME -> apps.nextcloud.com.cluster. NXDOMAIN
CNAME -> apps.nextcloud.com.svc.cluster. NXDOMAIN
CNAME -> nextcloud.com. NOERROR
CNAME -> nextcloud.com.cloud.svc.cluster. NXDOMAIN
CNAME -> nextcloud.com.cluster. NXDOMAIN
CNAME -> nextcloud.com.svc.cluster. NXDOMAIN
CNAME -> push-notifications.nextcloud.com. NOERROR
CNAME -> push-notifications.nextcloud.com.cloud.svc.cluster. NXDOMAIN
CNAME -> push-notifications.nextcloud.com.cluster. NXDOMAIN
CNAME -> push-notifications.nextcloud.com.svc.cluster. NXDOMAIN
CNAME -> pushfeed.nextcloud.com. NOERROR
CNAME -> pushfeed.nextcloud.com.cloud.svc.cluster. NXDOMAIN
CNAME -> pushfeed.nextcloud.com.cluster. NXDOMAIN
CNAME -> pushfeed.nextcloud.com.svc.cluster. NXDOMAIN
CNAME -> updates.nextcloud.com. NOERROR
CNAME -> updates.nextcloud.com.cloud.svc.cluster. NXDOMAIN
CNAME -> updates.nextcloud.com.cluster. NXDOMAIN
CNAME -> updates.nextcloud.com.svc.cluster. NXDOMAIN
CNAME -> www.nextcloud.com. NOERROR
CNAME -> www.nextcloud.com.cloud.svc.cluster. NXDOMAIN
CNAME -> www.nextcloud.com.cluster. NXDOMAIN
CNAME -> www.nextcloud.com.svc.cluster. NXDOMAIN
```

What I observed:

1. Every query for an `A` record contains a valid domain when cutting off the suffixes `.cloud.svc.cluster`, `.svc.cluster`, or `.cluster`
2. All of these queries are resolved correctly, i.e. non of these queries yielded a wrong result. I ran the queries with `dig` manually, and they yield the same results. Hence, I think DNS works correctly in my cluster.
3. The query `A -> nextcloud.com.cloud.svc.cluster.` is invalid. It is issued first. Then NC issues `A -> nextcloud.com.svc.cluster`, which is invalid. Then NC issues `A -> nextcloud.com.cluster`, which is invalid. Then NC, I guess, issues `A -> nextcloud.com`, which succeeds, hence CoreDNS does not log the request.
4. No. 3 does not seem to hold for CNAME queries, because the order is not always the same.
5. Still; the `.cloud.svc.cluster` suffixes should not be in the log, and would only be issued when appending the search domains. If I'm not mistaken, a resolver stub would _not_ issue a request with a search domain _after_ having issued the actual request, i.e. search domains are prepended before one issues the actual request.

**Comment by Rayn0r** [comment]
I still do not see how this is Nextcloud related. But in order to understand the issue, I'd like you to test something.
Which response do you get from `dig` or `nslookup` if you do the following:

1. Bring up the pod.
2. Log into it using `kubectl exec -it <pod-name> -- /bin/bash`
3. Edit your resolv.conf to contain nothing but:
```ini
nameserver 10.96.0.10 #put your DNS server's IP here
```
What do you get if you resolve the FQDN in question using `dig nextcloud.com`? Does it get resolved correctly?

**Comment by georglauterbach** [comment]
> I still do not see how this is Nextcloud related. But in order to understand the issue, I'd like you to test something. Which response do you get from `dig` or `nslookup` if you do the following:
> 
>     1. Bring up the pod.
> 
>     2. Log into it using `kubectl exec -it <pod-name> -- /bin/bash`
> 
>     3. Edit your resolv.conf to contain nothing but:
> 
> 
> ```ini
> nameserver 10.96.0.10 #put your DNS server's IP here
> ```
> 
> What do you get if you resolve the FQDN in question using `dig nextcloud.com`? Does it get resolved correctly?

Yes, it does:

```console
$ dig +short nextcloud.com
85.10.195.17
```

**Comment by georglauterbach** [comment]
I found the culprit. I noticed `getent` was the only program that seemed to ignore `options`. Hence I tried various combinations of options in `/etc/resolv.conf`, and I found that using `no-aaaa` would mess with `getent`. DNS was still working just find, but all options were seemingly ignored when using `no-aaaa`. As soon as I removed `no-aaaa` from the options list, `getent` started to conform to `options` in `/etc/resolv.conf`.

This is quite unexpected, because the [documentation of `/etc/resolv.conf`](https://man7.org/linux/man-pages/man5/resolv.conf.5.html) shows that support for `no-aaaa` exists since glibc 2.36, and NC 29.0.6 uses glibc 2.36-9+deb12u8.

Result: **Do not use `no-aaaa` in `options` in `/etc/resolv.conf`!** It should technically work, but it doesn't - at least as of now.
