### ISSUE TITLE
docker-compose example nginx triggers warning by setting X-Frame-Options "SAMEORIGIN"

### ISSUE THREAD

**Issue by dbroeh** [nextcloud/docker#928]
Greetings,

in current [nginx.conf](https://github.com/nextcloud/docker/blob/master/.examples/docker-compose/with-nginx-proxy/mariadb/fpm/web/nginx.conf) [L54](https://github.com/nextcloud/docker/blob/master/.examples/docker-compose/with-nginx-proxy/mariadb/fpm/web/nginx.conf#L54) and [L158](https://github.com/nextcloud/docker/blob/master/.examples/docker-compose/with-nginx-proxy/mariadb/fpm/web/nginx.conf#L158) lead to a security warning in Nextcloud's web application. Removing these lines (reverting to the older state) mitigates these warnings. The x-frame-option is also still (implicitly) set to sameorigin.

I am not sure if this only applies for my setup. Maybe somebody else could have a look and verify this.

**Comment by kowjens** [comment]
I cannot verify this issue. I've both set and no error, neither in nc nor securityheaders.com. (running latest stable updates nc 17.0.1)
kr Jens

**Comment by dbroeh** [comment]
Ok, I should have added specific nextcloud version number that I am using. It is version 16.0.6 (production channel). Nginx version tag is however latest unstable version 1.17.6-alpine.

**Comment by treyturner** [comment]
This is happening to me on 17.0.2.1.

I adjusted the header settings in two places in my nginx.conf, taken from https://docs.nextcloud.com/server/17/admin_manual/installation/nginx.html

```
add_header Referrer-Policy "no-referrer" always;
add_header X-Content-Type-Options "nosniff" always;
add_header X-Download-Options "noopen" always;
add_header X-Frame-Options "SAMEORIGIN" always;
add_header X-Permitted-Cross-Domain-Policies "none" always;
add_header X-Robots-Tag "none" always;
add_header X-XSS-Protection "1; mode=block" always;
```

I removed and recreated the whole app via `docker-compose`, but still have this warning in my Overview. This is an installation that was upgraded from v16 if that helps.

```
            Container                             Repository                    Tag         Image Id      Size
----------------------------------------------------------------------------------------------------------------
nextcloud_app_1                     nextcloud                                fpm-alpine   7838c59592f4   335 MB
nextcloud_cron_1                    nextcloud                                fpm-alpine   7838c59592f4   335 MB
nextcloud_db_1                      mariadb                                  latest       2f11cf2ec189   339 MB
nextcloud_letsencrypt-companion_1   jrcs/letsencrypt-nginx-proxy-companion   latest       d4955d798195   89.8 MB
nextcloud_proxy_1                   fpm_proxy                                latest       be2fa7294aaf   50.5 MB
nextcloud_redis_1                   redis                                    alpine       a49ff3e0d85f   27.9 MB
nextcloud_web_1                     fpm_web                                  latest       3418f6f9842b   19.5 MB
```

**Comment by J0WI** [comment]
Should be fixed in recent versions.

**Comment by treyturner** [comment]
@J0WI This is still impacting my installation after I just updated to 19.0.0.

My headers are configured as I reported above. Is there anything else I can/should do to try and resolve this?

**Comment by itouch5000** [comment]
I have the same problem with [this configuration](https://github.com/nextcloud/docker/tree/master/.examples/docker-compose/with-nginx-proxy/mariadb/fpm). Also no difference between nextcloud 18.x and 19.0.0.

**Comment by J0WI** [comment]
Have you updated the config to the [current example](https://docs.nextcloud.com/server/19/admin_manual/installation/nginx.html#nextcloud-in-the-webroot-of-nginx)?

**Comment by treyturner** [comment]
> Have you updated the config to the [current example](https://docs.nextcloud.com/server/19/admin_manual/installation/nginx.html#nextcloud-in-the-webroot-of-nginx)?

Yes, I just downed the app via docker-compose, replaced nginx.conf with the copy you suggested verbatim, and upped it again, and I still get this warning.

**Comment by aentwist** [comment]
Random guess: the header is *added*, not *set*, thus there are two of them. Then the JavaScript that checks this doesn't account for the headers being an array of 2 instead of a single thing, and an equality check fails, triggering the error condition.

Note that on nextcloud/server .htaccess it removes any X-Frame-Options headers, then adds the header back - effectively setting it.

**Comment by treyturner** [comment]
FWIW, this seemed to resolve itself with some update to the omnibus stack performed by [watchtower](https://github.com/containrrr/watchtower). I'm currently running `Nextcloud Hub 3 25.0.3` and these warnings are gone.

**Comment by aentwist** [comment]
This is a web server / proxy setting issue. The setting is still relevant for web servers / proxies because it is still in nextcloud/server .htaccess. Nextcloud version should make no difference unless you are using a version bundled with Apache.

The issue is probably caused by either not having `add_header X-Frame-Options "SAMEORIGIN" always;` or using [`add_header`](http://nginx.org/en/docs/http/ngx_http_headers_module.html#add_header) (which should always add a header, whether one is already set or not). It needs reproduction since it is old and no commit is linked to inspect potential code differences.
